#!/bin/bash
#export OS_TOKEN=`cat $OPENSTACK_DEPLOYER_PATH/keys/OS_TOKEN`
export OS_TOKEN=$KEYSTONE_ADMINTOKEN
export OS_URL=http://controller:35357/v$IDENTITY_API_VERSION
export OS_IDENTITY_API_VERSION=$IDENTITY_API_VERSION

echo "Exported OS_TOKEN[$OS_TOKEN] ; OS_URL[$OS_URL] ; OS_IDENTITY_API_VERSION[$OS_IDENTITY_API_VERSION]"
